#!/bin/bash

git clone https://github.com/YihanWangAstro/SpaceHub.git

wget https://dl.bintray.com/boostorg/release/1.70.0/source/boost_1_70_0.tar.gz

tar xzvf boost_1_70_0.tar.gz

rm boost_1_70_0.tar.gz

